# ? App name
spring.application.name=auth-service

# ? Server port
server.port=${PORT:8082}

# ? Database connection
spring.datasource.url=${AUTH_DB_URL:jdbc:mysql://localhost:3306/event_management_auth_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:viratkohli}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ? Optional (Hibernate auto-detects usually)
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect