# ? App name
spring.application.name=event-service

# ? Server port
server.port=${PORT:8081}

# ? Database connection
spring.datasource.url=${EVENT_DB_URL:jdbc:mysql://localhost:3306/event_management_event_db?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:viratkohli}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ? JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ? Optional (only if needed)
# spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect